apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app2-noprod1
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: ocm-placement-generator
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: app2-noprod1
      requeueAfterSeconds: 30
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
      name: '{{name}}-app2-noprod1'
    spec:
      destination:
        namespace: openshift-gitops
        server: https://kubernetes.default.svc
      project: default
      source:
        path: ./applications
        repoURL: https://github.com/giovannisciortino/acm_appset_app2.git
        targetRevision: noprod1
      syncPolicy:
        automated: {}
